<div class="endvLogo">
		<a href="https://www.endeavour.com.au/" target="_blank"><img src="img/endvLogo.png" id="endvlogoB" alt="Endeavours Logo" width="22%"></a>
</div>
<ul class="rslides">
  <li><img src="img/bannerImage1.jpg" alt="Banner Picture"></li>
  <li><img src="img/bannerImage2.jpg" alt="Banner Picture"></li>
  <li><img src="img/bannerImage4.jpg" alt="Banner Picture"></li>
  <li><img src="img/bannerImage3.jpg" alt="Banner Picture"></li>
</ul>

<div class="MBBLogo">
	<h2><span id="MBBLogoB">My Budget Buddy</span></h2>
	<div class="calcSymbols">
		<img src="img/logoSymbols.png" id="calcSymB" alt="Calculator Symbols">
	</div>
	<p> Giving you the ability to manage your own finances. </p>
</div>
<div class="bannerLine"></div>