<meta charset="utf-8">
<title><?php echo $page->title; ?></title>
<link rel="icon" type="image/ico" href="img/icons/wallet.ico"/>
<meta name="description" content="budgeting app for people with disabilities">

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<?php if ($page->useBootstrap) { ?>
    <!-- Import Bootstrap CSS files -->
    <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="bootstrap/css/bootstrap-theme.min.css">
<?php } ?>

<!-- customized style sheet -->
<link type="text/css" rel="stylesheet" href="styles/StyleSheet.css"/>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
